
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:4 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.3.1+2badb37d1 for .NET Framework
      Сборка начата 15.09.2023 12:42:39.
      Проект "C:\\Users\\79065\\OneDrive\\Рабочий стол\\C++ progs\\mp2-lab1-set-code\\CMakeFiles\\3.27.4\\CompilerIdC\\CompilerIdC.vcxproj" в узле 1 (целевые объекты по умолчанию).
      PrepareForBuild:
        Создание каталога "Debug\\".
        Создание каталога "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Создание "Debug\\CompilerIdC.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\Users\\79065\\OneDrive\\Рабочий стол\\C++ progs\\mp2-lab1-set-code\\CMakeFiles\\3.27.4\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Файл "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" удаляется.
        Обращение к "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Сборка проекта "C:\\Users\\79065\\OneDrive\\Рабочий стол\\C++ progs\\mp2-lab1-set-code\\CMakeFiles\\3.27.4\\CompilerIdC\\CompilerIdC.vcxproj" завершена (целевые объекты по умолчанию).
      
      Сборка успешно завершена.
          Предупреждений: 0
          Ошибок: 0
      
      Прошло времени 00:00:02.34
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/79065/OneDrive/Рабочий стол/C++ progs/mp2-lab1-set-code/CMakeFiles/3.27.4/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.3.1+2badb37d1 for .NET Framework
      Сборка начата 15.09.2023 12:42:42.
      Проект "C:\\Users\\79065\\OneDrive\\Рабочий стол\\C++ progs\\mp2-lab1-set-code\\CMakeFiles\\3.27.4\\CompilerIdCXX\\CompilerIdCXX.vcxproj" в узле 1 (целевые объекты по умолчанию).
      PrepareForBuild:
        Создание каталога "Debug\\".
        Создание каталога "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Создание "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\Users\\79065\\OneDrive\\Рабочий стол\\C++ progs\\mp2-lab1-set-code\\CMakeFiles\\3.27.4\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Файл "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" удаляется.
        Обращение к "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Сборка проекта "C:\\Users\\79065\\OneDrive\\Рабочий стол\\C++ progs\\mp2-lab1-set-code\\CMakeFiles\\3.27.4\\CompilerIdCXX\\CompilerIdCXX.vcxproj" завершена (целевые объекты по умолчанию).
      
      Сборка успешно завершена.
          Предупреждений: 0
          Ошибок: 0
      
      Прошло времени 00:00:01.92
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/79065/OneDrive/Рабочий стол/C++ progs/mp2-lab1-set-code/CMakeFiles/3.27.4/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:4 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/79065/OneDrive/\u0420\u0430\u0431\u043e\u0447\u0438\u0439 \u0441\u0442\u043e\u043b/C++ progs/mp2-lab1-set-code/CMakeFiles/CMakeScratch/TryCompile-bdw7w0"
      binary: "C:/Users/79065/OneDrive/\u0420\u0430\u0431\u043e\u0447\u0438\u0439 \u0441\u0442\u043e\u043b/C++ progs/mp2-lab1-set-code/CMakeFiles/CMakeScratch/TryCompile-bdw7w0"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/79065/OneDrive/Рабочий стол/C++ progs/mp2-lab1-set-code/CMakeFiles/CMakeScratch/TryCompile-bdw7w0'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_cb3ba.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        MSBuild version 17.3.1+2badb37d1 for .NET Framework
        Сборка начата 15.09.2023 12:42:45.
        Проект "C:\\Users\\79065\\OneDrive\\Рабочий стол\\C++ progs\\mp2-lab1-set-code\\CMakeFiles\\CMakeScratch\\TryCompile-bdw7w0\\cmTC_cb3ba.vcxproj" в узле 1 (целевые объекты по умолчанию).
        PrepareForBuild:
          Создание каталога "cmTC_cb3ba.dir\\Debug\\".
          Создание каталога "C:\\Users\\79065\\OneDrive\\Рабочий стол\\C++ progs\\mp2-lab1-set-code\\CMakeFiles\\CMakeScratch\\TryCompile-bdw7w0\\Debug\\".
          Создание каталога "cmTC_cb3ba.dir\\Debug\\cmTC_cb3ba.tlog\\".
        InitializeBuildStatus:
          Создание "cmTC_cb3ba.dir\\Debug\\cmTC_cb3ba.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_cb3ba.dir\\Debug\\\\" /Fd"cmTC_cb3ba.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
          Оптимизирующий компилятор Microsoft (R) C/C++ версии 19.33.31630 для x64
          (C) Корпорация Майкрософт (Microsoft Corporation).  Все права защищены.
          CMakeCCompilerABI.c
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_cb3ba.dir\\Debug\\\\" /Fd"cmTC_cb3ba.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\79065\\OneDrive\\Рабочий стол\\C++ progs\\mp2-lab1-set-code\\CMakeFiles\\CMakeScratch\\TryCompile-bdw7w0\\Debug\\cmTC_cb3ba.exe" /INCREMENTAL /ILK:"cmTC_cb3ba.dir\\Debug\\cmTC_cb3ba.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/79065/OneDrive/Рабочий стол/C++ progs/mp2-lab1-set-code/CMakeFiles/CMakeScratch/TryCompile-bdw7w0/Debug/cmTC_cb3ba.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/79065/OneDrive/Рабочий стол/C++ progs/mp2-lab1-set-code/CMakeFiles/CMakeScratch/TryCompile-bdw7w0/Debug/cmTC_cb3ba.lib" /MACHINE:X64  /machine:x64 cmTC_cb3ba.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_cb3ba.vcxproj -> C:\\Users\\79065\\OneDrive\\Рабочий стол\\C++ progs\\mp2-lab1-set-code\\CMakeFiles\\CMakeScratch\\TryCompile-bdw7w0\\Debug\\cmTC_cb3ba.exe
        FinalizeBuildStatus:
          Файл "cmTC_cb3ba.dir\\Debug\\cmTC_cb3ba.tlog\\unsuccessfulbuild" удаляется.
          Обращение к "cmTC_cb3ba.dir\\Debug\\cmTC_cb3ba.tlog\\cmTC_cb3ba.lastbuildstate".
        Сборка проекта "C:\\Users\\79065\\OneDrive\\Рабочий стол\\C++ progs\\mp2-lab1-set-code\\CMakeFiles\\CMakeScratch\\TryCompile-bdw7w0\\cmTC_cb3ba.vcxproj" завершена (целевые объекты по умолчанию).
        
        Сборка успешно завершена.
            Предупреждений: 0
            Ошибок: 0
        
        Прошло времени 00:00:02.03
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:4 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/79065/OneDrive/\u0420\u0430\u0431\u043e\u0447\u0438\u0439 \u0441\u0442\u043e\u043b/C++ progs/mp2-lab1-set-code/CMakeFiles/CMakeScratch/TryCompile-fzhr4e"
      binary: "C:/Users/79065/OneDrive/\u0420\u0430\u0431\u043e\u0447\u0438\u0439 \u0441\u0442\u043e\u043b/C++ progs/mp2-lab1-set-code/CMakeFiles/CMakeScratch/TryCompile-fzhr4e"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/79065/OneDrive/Рабочий стол/C++ progs/mp2-lab1-set-code/CMakeFiles/CMakeScratch/TryCompile-fzhr4e'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_8d215.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        MSBuild version 17.3.1+2badb37d1 for .NET Framework
        Сборка начата 15.09.2023 12:42:48.
        Проект "C:\\Users\\79065\\OneDrive\\Рабочий стол\\C++ progs\\mp2-lab1-set-code\\CMakeFiles\\CMakeScratch\\TryCompile-fzhr4e\\cmTC_8d215.vcxproj" в узле 1 (целевые объекты по умолчанию).
        PrepareForBuild:
          Создание каталога "cmTC_8d215.dir\\Debug\\".
          Создание каталога "C:\\Users\\79065\\OneDrive\\Рабочий стол\\C++ progs\\mp2-lab1-set-code\\CMakeFiles\\CMakeScratch\\TryCompile-fzhr4e\\Debug\\".
          Создание каталога "cmTC_8d215.dir\\Debug\\cmTC_8d215.tlog\\".
        InitializeBuildStatus:
          Создание "cmTC_8d215.dir\\Debug\\cmTC_8d215.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_8d215.dir\\Debug\\\\" /Fd"cmTC_8d215.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
          Оптимизирующий компилятор Microsoft (R) C/C++ версии 19.33.31630 для x64
          (C) Корпорация Майкрософт (Microsoft Corporation).  Все права защищены.
          CMakeCXXCompilerABI.cpp
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_8d215.dir\\Debug\\\\" /Fd"cmTC_8d215.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\79065\\OneDrive\\Рабочий стол\\C++ progs\\mp2-lab1-set-code\\CMakeFiles\\CMakeScratch\\TryCompile-fzhr4e\\Debug\\cmTC_8d215.exe" /INCREMENTAL /ILK:"cmTC_8d215.dir\\Debug\\cmTC_8d215.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/79065/OneDrive/Рабочий стол/C++ progs/mp2-lab1-set-code/CMakeFiles/CMakeScratch/TryCompile-fzhr4e/Debug/cmTC_8d215.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/79065/OneDrive/Рабочий стол/C++ progs/mp2-lab1-set-code/CMakeFiles/CMakeScratch/TryCompile-fzhr4e/Debug/cmTC_8d215.lib" /MACHINE:X64  /machine:x64 cmTC_8d215.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_8d215.vcxproj -> C:\\Users\\79065\\OneDrive\\Рабочий стол\\C++ progs\\mp2-lab1-set-code\\CMakeFiles\\CMakeScratch\\TryCompile-fzhr4e\\Debug\\cmTC_8d215.exe
        FinalizeBuildStatus:
          Файл "cmTC_8d215.dir\\Debug\\cmTC_8d215.tlog\\unsuccessfulbuild" удаляется.
          Обращение к "cmTC_8d215.dir\\Debug\\cmTC_8d215.tlog\\cmTC_8d215.lastbuildstate".
        Сборка проекта "C:\\Users\\79065\\OneDrive\\Рабочий стол\\C++ progs\\mp2-lab1-set-code\\CMakeFiles\\CMakeScratch\\TryCompile-fzhr4e\\cmTC_8d215.vcxproj" завершена (целевые объекты по умолчанию).
        
        Сборка успешно завершена.
            Предупреждений: 0
            Ошибок: 0
        
        Прошло времени 00:00:01.78
        
      exitCode: 0
...
